data = [["8 Mai (carrefour du)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Albert Auboin (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Albert Laurent (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Alfred de Musset (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Alphonse Daudet (rue) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Alsace (rue d’) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Amélie (avenue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Ampere (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Anatole France (rue)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["André Gide (rue)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Antoine Watteau (allée) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Arago (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Aulnais (petit sentier des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Avenir (rue de l’) côté avenue de Paris ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Avenir (rue de l’) côté avenue de la République ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Bagneux (rue de)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Bagneux (rue de) 13 (école Le Parc) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Beauséjour (allée)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Beranger (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Beranger (rue) 7, 9 et 51-53 - jardin d’école Béranger ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Beranger (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Berlioz (allée) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Blanchard (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Blanchard (villa) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Cadran solaire (allée du) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Cadran solaire (allée du) du 1 au  7 - côté impair  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Cadran solaire (allée du) du 2 au 14 - côté pair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Cèdre (allée du)  ", "Lundi, mercredi , vendredi soir ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Chalets (allée des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Champs fleuris (impasse des)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Charles Aznavour (allée) Présentation rue Gabriel Péri  ", "Lundi etvendredi soir ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Charles Aznavour (allée) Présentation avenue de Verdun  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Charlot (passage) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Chartres (rue de) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Chartres (rue de) 19, 21 et 23  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Châteaubriand (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Clément Perrière (avenue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Clément Perrière (avenue) 40  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Clos de la Marquise (villa du)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Colbert (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Corot (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Courtois (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Dahlias (allée des) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Defense (rue de la) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Denise (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Désiré (impasse)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Desporte (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Diderot (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Division Leclerc (avenue de la) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Division Leclerc (avenue de la) du 2 au 60 - côté pair  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Edgar Brandt (côté rue Voltaire)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Edgar Brandt (côté bd de Vanves)  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Edmond Rostand (rue)  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Eglise (place de l’)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Epargne (allée de l’) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Epargne (rue de l’) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Epée (allée de l’)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Esperance (impasse de l’) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Esther Cordier (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Estienne d’Orves (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Etangs (passage des)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Etangs (rue des)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Etienne Deforges (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Etienne Deforges (rue) du  11 au 23 - côté impair, 10 (multi-accueil Les Matelots), 12 et 30 (crècle Le Petit Poucet) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Eugène (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Eugène Dumur (place)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Eugénie (villa) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Europe (place de l’)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Fauvettes (rue des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Félix Faure (boulevard) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Félix Faure (boulevard) 65, 67 et 69  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Finlande (rue de) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Fontaine (allée de la)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Fontenay (rue de) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Fort (rue du) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Foyer (villa du)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["François Barrey (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["François Coppée (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["François Pinson (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["François Pinson (rue) du 51 au 59 - côté impair et du 52 au 58 - côté pair Présentation rue Pierre Curie  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Fraternité (allée de la)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Gabriel Péri (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gabriel Péri (rue) du 1 au  45 - côté impair et 51 et 53  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gabriel Péri (rue) du 2 au 50 - côté pair ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gambetta (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gambetta (rue) 19 - école Gambetta  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gare (rue de la)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gare (rue de la) 10, 18, 23, 30 et 32 ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Gay Lussac (impasse)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Gay Lussac (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Gay Lussac (rue) 20 école Gay Lussac et 55 collège Georges Sand ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Gay Lussac (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Général de Gaulle (carrefour du)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Geneviève (villa) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Genzano-di-Roma (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Geo Chavez (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["George Sand (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Georges Pompidou (allée)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Guy Moquet (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Guynemer (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Guynemer (rue) 2 (halte garderie) et cuisine centrale ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Henri Barbusse (allée)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Henri Gatinot (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Henri Gatinot (rue) 7 et 8 (école Langevin-Wallon)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Hoche (impasse) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Hoche (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Ile (rue de l’) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Ile (sentier de l’) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Iris (rue des)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Issy (voie d’)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jacqueline (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Jean Bouin (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Bouin (rue) 31 ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Dupuis (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Jean Jaures (avenue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Jean Jaures (rue) du 1 au 29 - côté impair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Jean Jaures (rue) du 2 au 26 - côté pair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Jean Jaures (rue) du 28 au 60 et du 68 au 120 - côté pair ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Jean Jaures (rue) du 31 au 119 - côté impair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Jean Jaures (rue) 62-66 - école Jean-Jaurès ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Jean Macé (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Jean Macé (rue) 9 bis - crèche La flûte enchantée ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Jean Mermoz (place) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Mermoz (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Mermoz (rue) 6 - école Joliot Curie  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Moreas (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jean Richepin (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jeanne d’Arc (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Jeanne Hachette (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Jean-Pierre Timbaud (rue) 1, 2, 4, 6, 8 et 10 ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Jean-Pierre Timbaud (rue) du 14 au 36 - côté pair ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudii matin  ", "Secteur B ", "Secteur 1"],
["Jean-Pierre Timbaud (rue) du 21 au 37 - côté impair ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudii matin  ", "Secteur B ", "Secteur 1"],
["José Maria de Heredia (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Jules Vedrines (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Kleber (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Kleber (rue) 20, 22, 24, 30 ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Lasègue (impasse) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Lasègue (passage) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Lasègue (rue) du 1 au 21 - côté impair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Lasègue (rue) du 2 au 14 - côté pair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Lasègue (rue) du 20 au 160 - côté pair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Lasègue (rue) du 31 au 151 - côté impair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Leconte de Lisle (rue)  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Le Mesnil (villa) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Lecaillon (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Léonard Mafrand (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Libération (place de la)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Liberté (impasse) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Liberté (boulevard de la) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Liberté (boulevard de la) 16, 17, 18, 34, 40, 42, 46  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Lilas (rue des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Louis Blériot (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Louise Auvry (villa)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Louveau (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Lucien Sampaix (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Lucien Sampaix (rue) 45 et 47 ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Madeleine (passage) Présentation rue des Fauvettes  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Madeleine (villa) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Mairie (rue de la)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Malakoff (rue de) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Malakoff (rue de) 4, 34 - multi-accueil Le Petit Prince 39-41 ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Marceau (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Marcel (impasse)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Marcelin Berthelot (avenue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Marguerite (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Maryse Bastié (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Maurice (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Merseburg (rue de)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Mesie (villa La)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Montesquieu (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Mozart (allée)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Noise (impasse de la) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Orme aux chiens (sentier de l’) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Paix (avenue de la) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["39 (école Marcel Doret) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Paix (impasse de la)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Panorama (rue du) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Paris (avenue de) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Paroseaux (sentier des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Paroseaux (villa des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Paroseaux (villa des) 1, 3 et 25 - école Les Sablons  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Pasteur (rue) côté avenue de Paris  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Pasteur (rue) côté rue de Mersburg  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Pasteur (villa) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Paul Bert (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Paul Vaillant Couturier (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Peyronnet (allée) ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Perrotin (rue)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Petras (voie) côté rue des Fauvettes  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Petras (voie) côté rue Pierre Curie ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Peupliers (villa des) Présentation sur l’avenue de Paris  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Pierre Brossolette (rue) du 1 au 13 - côté impair ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierre Brossolette (rue) du 2 au 14 - côté pair ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierre Brossolette (rue) du 20 au 80 et du 110 126 - côté pair  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Pierre Brossolette (rue) du 21bis au 65 et du 69 au 83 - côté impair ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Pierre Brossolette (rue) du 82 au 110 - côté pair, 52 (crèche Les P’tits Loups) et 67 ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Pierre Curie (impasse)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Pierre Curie (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Pierre Loti (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Pierre Semard (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Pierrelais (rue des)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierrelais (rue des) 1, 9, 15, 31 et 33 ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierrettes (rue des)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierrettes (rue des) du 52 au 60 - côté pair et 39 (collège Paul Eluard)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Pierrier (passage du) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Plateau (rue du)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Plateau (sentier du)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Prévoyants (allée des)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Pris-Pris (allée des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Progrès (allée du)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Rameau (allée)  ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Ravel (allée) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Renée (allée) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["République (avenue de la) du 1 au 19 - côté impair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["République (avenue de la) du 21 au 25 - côté impair ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["République (avenue de la) du 35 au 149 et du 157 au 185 - côté impair ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["République (avenue de la) du 2 au 36 - côté pair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["République (avenue de la) du 40 au 220 - côté pair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["République (avenue de la) du 151 au  155 - côté impair  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Roissys (rue des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Roissys (villa des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Roland Garros (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Roses (villa des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Rosiers (villa des) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Sablons (allée des) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Sadi Carnot (rue) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Saint Exupéry (avenue)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Samson (impasse)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Sarments (allée des)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 3"],
["Savoie (allée de la)  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Savoie (petit sentier de la) côté allée de la Savoie  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Savoie (petit sentier de la) côté rue de la Savoie  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Savoie (rue de la)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Square (impasse du) ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 4"],
["Stalingrad (boulevard)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Stalingrad (boulevard) 1, 3, 15 et 19 (crèche Les Maronniers) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Sully Prudhomme (rue) ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Suzanne (villa) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Suzanne Fouche (allée)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Traverse loup (allée du)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Tybyrs (sentier des)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Union (rue de l’) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 2"],
["Vanves (boulevard de) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Vanves (boulevard de) 9, 18, 52, 61, 63 et 71 ", "Lundi, mercredi, vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Vauban (allée)  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur A ", "Secteur 4"],
["Verdun (avenue de) du 1 au 57 - côté impair et 71 , 73, 117, 119 et 121  ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Verdun (avenue de) du 75 au 115 - côté impair ", "Lundi et vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Verdun (avenue de) du 2 au 62 - côté pair ", "Lundi, mercredi, vendredi soir  ", "Mardi soir  ", "Mercredi matin  ", "Secteur B ", "Secteur 3"],
["Verdun (avenue de) du 68 au 76 - côté pair Présentation villa des Paroseaux ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"],
["Verdun (avenue de) du 136 au 156 - côté pair  ", "Lundi et vendredi soir  ", "Mardi soir  ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Vergers (rue des) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Verges (villa)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Victor Hugo (rue) ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 3"],
["Voltaire (rue)  ", "Lundi et vendredi matin ", "Mardi matin ", "Jeudi matin ", "Secteur B ", "Secteur 1"]]
