data = [["12 Février 1934 (avenue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["19 Mars 1962 (carrefour du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["19 Mars 1962 (rue du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["14 Juillet (1 place du)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["14 Juillet (place du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["11 Novembre (place du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Adnot (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Adolphe Pinard (boulevard)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Albert Marie (impasse)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Albert Samain (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Alexis Martin (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Alfred de Musset (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Ampère (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Anatole France (avenue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["André Coin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["André Rivoire (rue)", "PAV face aux n¡2, 5, 9 et 12", "PAV face aux n¡2, 5, 9 et 12", "Mercredi matin", "Secteur 1"],
["André Rivoire - Ecole maternelle et élémentaire Paul Langevin (15 rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["André Sabatier (impasse)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["André Sabatier (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["André Sabatier (sentier)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Arblade (avenue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Archin (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Arcole (passage d')", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Arcueil (villa d')", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Arthur Rimbaud (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Augustin Dumont (avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Augustine Variot (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Avaulée (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Bas Garmants (sentier des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Bel-Air (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Benjamin Raspail (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Beranger (2 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Béranger (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Bourgeois (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Cacheux (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Camelinat (50-52 boulevard)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Camelinat (90 boulevard)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Camélinat (boulevard)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Carnot (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Carnot (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Caron (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Cerisiers (sentier des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Césaire (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Charles Baudelaire (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Charles de Gaulle du n¡1 au n¡55 (boulevard)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Châtillon (impasse de)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Chauvelot (14 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Chauvelot (rue)", "Lundi et vendredi soir + PAV face au n¡38 bis", "Jeudi soir + PAV face au n¡38 bis", "Mercredi matin", "Secteur 2"],
["Chemin de Fer (villa du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Christiane (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Clos (impasse du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Clos Montholon (place du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Colonel Fabien (8 boulevard du)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Colonel Fabien (11 boulevard du)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Colonel Fabien (boulevard du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Colonel Fabien (carrefour du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Coulée Verte (square de la)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Croix (sentier de la)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Danicourt (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Danton (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Depinoy (place)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Docteur Ménard (rue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Drouet (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Drouet Peupion (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Ecoles (villa des)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Economes (villa des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Edgar Quinet (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Emile Zola (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Ernest Renan (rue)", "Lundi et vendredi soir + PAV face au n¡20", "Jeudi soir + PAV face au n¡20", "Mercredi matin", "Secteur 2"],
["Espérance (allée de l')", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Etienne Dolet (78-80-82-84 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Etienne Dolet (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Eugène Varlin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Féburier (square)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Ferri (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Fosses Rouges (impasse des)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Fosses Rouges (sentier des)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["François Belloeuvre (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Francois Coppée (1 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Francois Coppée (11 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["François Coppée (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["François Fabié (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Frédéric Fournier (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Frères Vigouroux (boulevard des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Gabriel Crié (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Gabriel Péri (boulevard) Du 1 au 29 - côté impair", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Gabriel Péri (boulevard) Du 2 au 42 - côté pair", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Gabriel Péri (boulevard) Du 31 au 175 - côté impair", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Gabriel Péri (boulevard) Du 44 au 186 - côté pair", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Gallieni (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Gambetta (rue)", "Lundi et vendredi soir + PAV face au n¡5 et 34-36", "Jeudi soir + PAV face au n¡5 et 34-36", "Mercredi matin", "Secteur 2"],
["Garmants (rue des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Garmants (sentier des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Général Malleret-Joinville (rue du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Geneviève (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Georges Brassens (rue)", "PAV face aux n¡4, 5 et 10", "PAV face aux n¡4, 5 et 10", "Mercredi matin", "Secteur 1"],
["Georges Henri (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Germaine (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Groux (impasse des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Guy Moquet (50 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Guy Moquet (rue) Du 1 au 89 - côté impair", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Guy Moquet (rue) Du 2 au 88 - côté pair ", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Guy Moquet (rue) Du 91 au 107 - côté impair ", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Guy Moquet (rue) Du 90 au 110 - côté pair", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Hébécourt (rue d')", "Lundi,mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Henri Barbusse (boulevard)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Henri Martin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Hoche (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Hoche (rue)", "Lundi, mercredi et vendredi matin + PAV face aux n¡14 et 75", "Jeudi matin + PAV face aux n¡14 et 75", "Mercredi matin", "Secteur 1"],
["Hubert Ponscarme (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Irène et Frédéric Joliot-Curie (avenue)", "Lundi, mercredi et vendredi soir + PAV face aux n¡4 et 8/10", "Jeudi soir + PAV face aux n¡4 et 8/10", "Mercredi matin", "Secteur 1"],
["Iris (villa des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Issy (voie d')", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jacques Brel (allèe)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jacques Prévert (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Jean Jaurès (avenue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Jean Jaurès (cité)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jean Lurèat (rue)", "PAV face aux n¡1, 5 et 11 et angle rue Jean Moulin", "PAV face aux n¡1, 5 et 12 et angle rue Jean Moulin", "Mercredi matin", "Secteur 1"],
["Jean Mermoz (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jean Moulin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Jean-Jacques Rousseau (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Jeanne (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jules Dalou (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jules Ferry (avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Jules Guesde (74 rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jules Guesde (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Jules Védrines (rue)", "Lundi et vendredi matin + PAV face aux n¡31, 33Bis, 35 Bis, 37 Bis et 39 Bis", "Jeudi matin + PAV face aux n¡31, 33Bis, 35 Bis, 37 Bis et 39 Bis", "Mercredi matin", "Secteur 1"],
["Labrousse (villa)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Laforest (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Larousse (passage) Du 1 au 11 bis - côté impair - et du 2 au 8 - côté pair - présentation sur la rue Ernest Renan", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Larousse (passage) Du 13 au 23 - côté impair - et du 2 au 18 - côté pair - présentation sur l'avenue Pierre Larousse", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Lavoir (rue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Ledru-Rollin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Léger (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Legrand (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Léo Figuères (place)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Léon Salagnac (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Leroyer (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Loret (villa)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Lorraine (rue de)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Louis Blanc (5 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Louis Blanc (Crèche Wilson) (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Louis Blanc (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Louis Girard (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Louis Mercier (rue)", "PAV face aux n¡1 et 2", "PAV face aux n¡1 et 2", "Mercredi matin", "Secteur 1"],
["Lucien et Edouard Gerber (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Marc Seguin (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Marceau (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Maréchal Leclerc (2 avenue du)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Maréchal Leclerc (avenue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Marguerite (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Marie Lahy Hollebecque (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Marie-Antoinette (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Marie-Jeanne (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Marie-Louise (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Marotte (villa)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Mathilde (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Maurice Bouchor (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Maurice Thorez (avenue)", "Lundi et vendredi soir + PAV face aux n¡13/15/17 et aux n¡ 7/9/11", "Jeudi soir + PAV face aux n¡13/15/17 et aux n¡ 7/9/11", "Mercredi matin", "Secteur 1"],
["Maurice Thorez (mail)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Maximilien Robespierre (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Michelin (passage)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Mirabeau (allée)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Négriers (impasse des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Neuve Montholon (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Nicomédès Pascual (rue) Du n¡1 au n¡15 - coté impair", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Nicomédès Pascual (rue) Du n¡2 au n¡18 - coté pair", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Nicomédès Pascual (rue) Du n¡17 au n¡21 - coté impair", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Nicomédès Pascual (rue) Du n¡ 20 au n¡34 - coté pair", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Nord (22 passage du)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Nord (passage du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Nouzeaux (sentier des)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Pasteur (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Paul Bert (6 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Paul Bert (rue) Du n¡1 au n¡21 - coté impair", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Paul Bert (rue) Du n¡2 au n¡22 - côté pair", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Paul Bert (rue) Du n¡23 au n¡51 - côté impair", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paul Bert (rue) Du n¡ 24 au n¡52 - côté pair", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paul Eluard (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paul Vaillant Couturier (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paul Valéry (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paul Verlaine (rue)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Paulette (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Perrot (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Petit Vanves (passage du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Pierre Brossolette (210 avenue)", "PAV face aux halls 1, 5 et 12", "PAV face aux halls 1, 5 et 12", "Mercredi matin", "Secteur 1"],
["Pierre Brossolette (avenue) Du n¡2 au n¡146", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Brossolette (avenue) Du n¡148 au n¡244", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Pierre Curie (impasse)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Pierre Larousse (53 avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (54 avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (56 avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (58 avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (83 avenue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (avenue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Larousse (square)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Pierre Simon (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Pierre Valette (rue)", "Lundi, mercredi et vendredi soir + PAV aux n¡24 ˆ 46 et ZAC Dolet Brossolette", "Jeudi soir + PAV aux n¡ 24 ˆ 46 et ZAC Dolet Brossolette", "Mercredi matin", "Secteur 1"],
["Pierrier (passage du)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Ponscarme (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Président Wilson (avenue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Puzin (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Raffin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Raymond David (rue)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Raymond Fassin (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Renault (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["République (place de la)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Ressort (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Richard (passage)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Roissys (rue des)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Rose (villa)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Rouget de Lisle (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Sablonnière (sentier de la)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Sabot (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Sainte-Hélène (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Salvador Allende (rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Savier (rue)", "Lundi et vendredi soir + PAV au n¡35", "Jeudi soir + PAV au n¡35", "Mercredi matin", "Secteur 2"],
["Scelle (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Stade Municipal (rue du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Stalingrad (28 boulevard de)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Stalingrad (29 boulevard de)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Stalingrad (32 boulevard de)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Stalingrad (boulevard de)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Théâtre (passage du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Tir (impasse du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Tir (sentier du)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Tissot (allée)", "Lundi, mercredi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Tour (rue de la)", "Lundi et vendredi soir + PAV face aux n4, 12, 16 et angle rue Ernest Renan", "Jeudi soir + PAV face aux n4, 12 et 16 et angle rue Ernest Renan", "Mercredi matin", "Secteur 2"],
["Ernest Renan", "Jeudi soir + PAV face aux n¡4, 12 et 16 et angle rue Ernest Renan", "Jeudi soir + PAV face au n20", "Mercredi matin", "Secteur 2"],
["Vallée (rue de la)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Vanves (impasse de)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"],
["Vauban (impasse)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Victor Hugo (16 rue)", "Lundi, mercredi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Victor Hugo (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 2"],
["Vincent Morris (rue)", "Lundi et vendredi soir", "Jeudi soir", "Mercredi matin", "Secteur 1"],
["Voltaire (rue)", "Lundi et vendredi soir + PAV face aux n¡17 et 29", "Jeudi soir + PAV face aux n¡17 et 29", "Mercredi matin", "Secteur 2"],
["Yvonne (villa)", "Lundi et vendredi matin", "Jeudi matin", "Mercredi matin", "Secteur 1"]]
